image: php:7.4

cache:
  paths:
    - vendor/
    - composer.lock

before_script:
  - apt-get update -yqq
  - apt-get install -yqq git libzip-dev unzip
  - docker-php-ext-install zip
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install --ignore-platform-reqs

phpstan:
  allow_failure: false
  script:
    - vendor/bin/phpstan analyse . --error-format=junit --no-interaction > phpstan-report.xml
  artifacts:
    when: always
    expose_as: phpstan-report
    paths:
      - phpstan-report.xml
    reports:
      junit: phpstan-report.xml

phpmd:
  allow_failure: false
  script:
    - vendor/bin/phpmd . xml phpmd.xml --exclude vendor > phpmd-report.xml
  artifacts:
    when: always
    expose_as: phpmd-report
    paths:
      - phpmd-report.xml
    reports:
      junit: phpmd-report.xml

phpcsfixer:
  allow_failure: false
  script:
    - vendor/bin/php-cs-fixer fix -v --format junit --dry-run > phpcsfixer-report.xml
  artifacts:
    when: always
    expose_as: phpcsfixer-report
    paths:
      - phpcsfixer-report.xml
    reports:
      junit: phpcsfixer-report.xml
